### ISSUE TITLE
Flatten fails, unable to follow a ptr (dev)

### ISSUE THREAD

**Issue by EfraimFeinstein** [opensiddur/opensiddur#194]
Flatten on https://db-dev.jewishliturgy.org/exist/restxq/api/data/original/%D7%91%D7%A8%D7%90%D7%A9%D7%99%D7%AA%20%D7%90/flat fails with:

```
In function:
	uri:range(node(), node(), xs:boolean) [224:20:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:follow(node()*, xs:integer, xs:string?, xs:boolean?, xs:boolean?) [214:7:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:fast-follow(xs:string, node(), xs:integer, xs:boolean?, xs:boolean, xs:string?) [175:3:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:fast-follow(xs:string, node(), xs:integer, xs:boolean?, xs:boolean) [165:3:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:fast-follow(xs:string, node(), xs:integer, xs:boolean?) [287:11:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:follow-tei-link(element(), xs:integer, xs:string?, xs:boolean?, xs:boolean?) [261:3:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	uri:follow-tei-link(element(), xs:integer, xs:string?, xs:boolean?) [437:18:/db/apps/opensiddur-server/modules/follow-uri.xqm]
	flatten:tei-ptr(element(), map(*)) [311:46:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:flatten(node()*, map(*)) [614:11:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:element(element(), map(*)) [317:19:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:flatten(node()*, map(*)) [614:11:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:element(element(), map(*)) [317:19:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:flatten(node()*, map(*)) [758:9:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:order-flattened(node()*) [757:7:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:j-layer(element(), map(*)) [310:46:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:flatten(node()*, map(*)) [330:5:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:identity(element(), map(*)) [312:51:/db/apps/opensiddur-server/transforms/flatten.xqm]
	flatten:flatten(node()*, map(*)) [283:19:/db/apps/opensiddur-server/transforms/flatten.xqm]
	common:apply-at(node()*, node()*, function(*), map(*)) [293:11:/db/apps/opensiddur-server/modules/common.xqm]
	common:apply-at(node()*, node()*, function(*), map(*)) [293:11:/db/apps/opensiddur-server/modules/common.xqm]
	common:apply-at(node()*, node()*, function(*), map(*)) [296:25:/db/apps/opensiddur-server/modules/common.xqm]
	common:apply-at(node()*, node()*, function(*), map(*)) [292:3:/db/apps/opensiddur-server/modules/common.xqm]
	flatten:flatten-document(document-node(), map(*)) [-1:-1:/db/apps/opensiddur-server/transforms/flatten.xqm]
	partial738427731(document-node()) [271:29:/db/apps/opensiddur-server/modules/format.xqm]
	mirror:store(xs:string, xs:string, xs:string, item()+) [448:7:/db/apps/opensiddur-server/modules/mirror.xqm]
	mirror:apply-if-outdated(xs:string, item(), function(*), item(), function(*)?) [152:17:/db/apps/opensiddur-server/modules/mirror.xqm]. XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: uri:range($left as node(), $right as node(), $allow-copies as xs:boolean) node()*. Expected cardinality: exactly one, got 0. [at line 169, column 17, source: /db/apps/opensiddur-server/modules/format.xqm]
In function:
	format:apply-if-outdated(xs:string, map(*), xs:string, item(), function(*), document-node(), function(*)?) [127:5:/db/apps/opensiddur-server/modules/format.xqm]
	format:apply-if-outdated(xs:string, map(*), xs:string, item(), function(*), document-node()) [273:5:/db/apps/opensiddur-server/modules/format.xqm]
	format:flatten(document-node(), map(*), document-node()) [305:7:/db/apps/opensiddur-server/modules/format.xqm]
	format:apply-if-outdated(xs:string, map(*), xs:string, item(), function(*), document-node()) [301:5:/db/apps/opensiddur-server/modules/format.xqm]
	format:merge(document-node(), map(*), document-node()) [329:7:/db/apps/opensiddur-server/modules/format.xqm]
	format:apply-if-outdated(xs:string, map(*), xs:string, item(), function(*), document-node()) [325:5:/db/apps/opensiddur-server/modules/format.xqm]
	format:resolve(document-node(), map(*), document-node()) [343:5:/db/apps/opensiddur-server/modules/format.xqm]
	flatten:display(node()*, map(*)) [342:3:/db/apps/opensiddur-server/transforms/flatten.xqm]
	format:display-flat(document-node(), map(*), document-node()) [384:5:/db/apps/opensiddur-server/modules/format.xqm]
	orig:get-flat(xs:string) [-1:-1:/db/apps/opensiddur-server/api/data/original.xqm]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by EfraimFeinstein** [comment]
Cleared cache -- unable to reproduce; could this have been caused by resource contention? If so, how to prevent it in the future?
